# Chapter 8: Neural Networks
## Training a Classifier on the *Salammbô* Dataset with Keras

We use three classes: French, English, and German

Programs from the book: [_Python for Natural Language Processing_](https://link.springer.com/book/9783031575488)

__Author__: Pierre Nugues

## Modules

We first need to import some modules

In [1]:
import numpy as np

In [2]:
import os
os.environ["KERAS_BACKEND"] = 'torch'

In [3]:
import keras

### Reading the dataset
We can read the data from a file with the svmlight format or directly create numpy arrays

In [4]:
X = np.array(
    [[35680, 2217], [42514, 2761], [15162, 990], [35298, 2274],
     [29800, 1865], [40255, 2606], [74532, 4805], [37464, 2396],
     [31030, 1993], [24843, 1627], [36172, 2375], [39552, 2560],
     [72545, 4597], [75352, 4871], [18031, 1119], [36961, 2503],
     [43621, 2992], [15694, 1042], [36231, 2487], [29945, 2014],
     [40588, 2805], [75255, 5062], [37709, 2643], [30899, 2126],
     [25486, 1784], [37497, 2641], [40398, 2766], [74105, 5047],
     [76725, 5312], [18317, 1215]
     ])

y = np.array(
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

We add German data and we adjust `y`

In [5]:
X_de = np.array(
    [[37599, 1771], [44565, 2116], [16156, 715], [37697, 1804],
     [29800, 1865], [42606, 2146], [78242, 3813], [40341, 1955],
     [31030, 1993], [26676, 1346], [39250, 1902], [41780, 2106],
     [72545, 4597], [79195, 3988], [19020, 928]
     ])

X = np.vstack((X, X_de))

y = np.array(
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Scaling the Data
Scaling and normalizing are usually very significant with neural networks. We use sklean transformers. They consist of two main methods: `fit()` and `transform()`.

### Normalizing

In [6]:
from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
X_norm = normalizer.fit_transform(X)
X_norm[:4]

array([[0.99807515, 0.06201605],
       [0.99789783, 0.06480679],
       [0.99787509, 0.06515607],
       [0.99793128, 0.06428964]])

### Standardizing

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler(with_mean=True, with_std=True)
X_scaled = scaler.fit_transform(X_norm)
X_scaled[:4]

array([[-0.03108396,  0.0944527 ],
       [-0.4126595 ,  0.44232074],
       [-0.46160343,  0.48585864],
       [-0.34067721,  0.37785758]])

In [8]:
Y_cat = keras.utils.to_categorical(y)
Y_cat[:4]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

## Creating a Model

We set a seed to have reproducible results

In [9]:
np.random.seed(1337)

We create a classifier equivalent to a logistic regression with `softmax`

In [10]:
model = keras.Sequential([
    keras.layers.Dense(3, activation='softmax')
])

Or with one hidden layer

In [11]:
model2 = keras.Sequential([
    keras.layers.Dense(5, activation='relu'),
    # layers.Dropout(0.5),
    keras.layers.Dense(3, activation='softmax')
])

To try the network with one hidden layer, set `simple` to false

In [12]:
simple = False
if not simple:
    model = model2

## Fitting the Model

We compile and fit the model

In [13]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])
model.fit(X_scaled, Y_cat, epochs=50, batch_size=1)

Epoch 1/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5778 - loss: 1.0230
Epoch 2/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4667 - loss: 0.9254
Epoch 3/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6222 - loss: 0.8500
Epoch 4/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6444 - loss: 0.7902
Epoch 5/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6444 - loss: 0.7434
Epoch 6/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6667 - loss: 0.7065
Epoch 7/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6667 - loss: 0.6766
Epoch 8/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6667 - loss: 0.6521
Epoch 9/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6889 - loss: 0.6307
Epoch 10/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6889 - loss: 0.6104
Epoch 11/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6889 - loss: 0.5906
Epoch 12/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6889 - lo

### The weights

In [14]:
model.get_weights()

[array([[ 0.7770449 , -1.5520418 , -0.59897363, -0.19602431,  0.99283165],
        [-0.47461706,  1.3037754 , -0.63470554, -1.3302276 , -0.29901943]],
       dtype=float32),
 array([ 1.1750546 ,  0.01198427, -0.09109583,  1.02463   ,  0.04586841],
       dtype=float32),
 array([[ 0.85848355, -0.8960729 ,  1.2957262 ],
        [ 0.01871657,  1.6688223 , -0.8203756 ],
        [ 0.15480804, -0.6890558 , -0.30334234],
        [ 0.40854606, -1.1373091 ,  0.9112625 ],
        [-1.066297  ,  0.46666935,  0.27385822]], dtype=float32),
 array([ 0.8943607 , -0.45795596, -0.43640602], dtype=float32)]

## Prediction
### Probabilities

We compute the probabilities to belong to the classes for all the training set

In [15]:
Y_pred_proba = model.predict(X_scaled)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step 


In [16]:
np.set_printoptions(precision=3, suppress=True)
Y_pred_proba

array([[0.628, 0.008, 0.364],
       [0.691, 0.197, 0.112],
       [0.64 , 0.272, 0.088],
       [0.733, 0.116, 0.151],
       [0.669, 0.014, 0.317],
       [0.712, 0.161, 0.127],
       [0.731, 0.122, 0.147],
       [0.742, 0.07 , 0.189],
       [0.74 , 0.094, 0.166],
       [0.604, 0.32 , 0.076],
       [0.569, 0.364, 0.066],
       [0.713, 0.159, 0.128],
       [0.724, 0.035, 0.241],
       [0.72 , 0.146, 0.134],
       [0.621, 0.007, 0.372],
       [0.129, 0.865, 0.006],
       [0.052, 0.947, 0.002],
       [0.391, 0.577, 0.032],
       [0.049, 0.95 , 0.001],
       [0.2  , 0.789, 0.011],
       [0.035, 0.964, 0.001],
       [0.198, 0.791, 0.011],
       [0.019, 0.981, 0.   ],
       [0.042, 0.957, 0.001],
       [0.02 , 0.98 , 0.   ],
       [0.015, 0.985, 0.   ],
       [0.059, 0.939, 0.002],
       [0.087, 0.91 , 0.003],
       [0.032, 0.967, 0.001],
       [0.406, 0.559, 0.035],
       [0.009, 0.   , 0.991],
       [0.01 , 0.   , 0.99 ],
       [0.004, 0.   , 0.996],
       [0.

We recompute it with matrices

In [17]:
from keras.activations import softmax, relu
import torch  # because of the backend set to torch
X = torch.from_numpy(X_scaled).float()
W = [w.value for w in model.weights]
X = X.to(W[0].device)

if simple:
    print(softmax((X @ W[0] + W[1]))[:4])
else:
    print(softmax((relu(X@W[0] + W[1]))@W[2] + W[3])[:4])

tensor([[0.6283, 0.0078, 0.3639],
        [0.6910, 0.1971, 0.1119],
        [0.6402, 0.2716, 0.0882],
        [0.7330, 0.1164, 0.1506]], device='mps:0', grad_fn=<SliceBackward0>)


### Classes

In [18]:
y_pred = np.argmax(Y_pred_proba, axis=-1)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2,
       2])

## Loss
We recompute the loss

For one observation

In [19]:
- Y_cat[0] @ np.log(Y_pred_proba[0]).T

np.float64(0.4647783041000366)

For the dataset

In [20]:
-np.mean(np.log(Y_pred_proba[range(0, len(y)), y]))

np.float32(0.2782638)

## Evaluation

With Keras

In [21]:
model.evaluate(X_scaled, Y_cat)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9333 - loss: 0.2783


[0.27826380729675293, 0.9333333373069763]

With sklearn

In [22]:
from sklearn.metrics import classification_report

print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91        15
           1       1.00      1.00      1.00        15
           2       1.00      0.80      0.89        15

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45



We computed the accuracy from the training set. This is not a good practice. We should use a dedicated test set instead.