# Chapter 8: Neural Networks
## Training a Classifier on the *Salammbô* Dataset with Keras

We use three classes: French, English, and German

Programs from the book: [_Python for Natural Language Processing_](https://link.springer.com/book/9783031575488)

__Author__: Pierre Nugues

## Modules

We first need to import some modules

In [1]:
import numpy as np

In [2]:
import os
os.environ["KERAS_BACKEND"] = 'torch'

In [3]:
import keras

### Reading the dataset
We can read the data from a file with the svmlight format or directly create numpy arrays

In [4]:
X = np.array(
    [[35680, 2217], [42514, 2761], [15162, 990], [35298, 2274],
     [29800, 1865], [40255, 2606], [74532, 4805], [37464, 2396],
     [31030, 1993], [24843, 1627], [36172, 2375], [39552, 2560],
     [72545, 4597], [75352, 4871], [18031, 1119], [36961, 2503],
     [43621, 2992], [15694, 1042], [36231, 2487], [29945, 2014],
     [40588, 2805], [75255, 5062], [37709, 2643], [30899, 2126],
     [25486, 1784], [37497, 2641], [40398, 2766], [74105, 5047],
     [76725, 5312], [18317, 1215]
     ])

y = np.array(
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

We add German data and we adjust `y`

In [5]:
X_de = np.array(
    [[37599, 1771], [44565, 2116], [16156, 715], [37697, 1804],
     [29800, 1865], [42606, 2146], [78242, 3813], [40341, 1955],
     [31030, 1993], [26676, 1346], [39250, 1902], [41780, 2106],
     [72545, 4597], [79195, 3988], [19020, 928]
     ])

X = np.vstack((X, X_de))

y = np.array(
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Scaling the Data
Scaling and normalizing are usually very significant with neural networks. We use sklean transformers. They consist of two main methods: `fit()` and `transform()`.

### Normalizing

In [6]:
from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
X_norm = normalizer.fit_transform(X)
X_norm[:4]

array([[0.99807515, 0.06201605],
       [0.99789783, 0.06480679],
       [0.99787509, 0.06515607],
       [0.99793128, 0.06428964]])

### Standardizing

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler(with_mean=True, with_std=True)
X_scaled = scaler.fit_transform(X_norm)
X_scaled[:4]

array([[-0.03108396,  0.0944527 ],
       [-0.4126595 ,  0.44232074],
       [-0.46160343,  0.48585864],
       [-0.34067721,  0.37785758]])

In [8]:
Y_cat = keras.utils.to_categorical(y)
Y_cat[:4]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

## Creating a Model

We set a seed to have reproducible results

In [9]:
np.random.seed(1337)

We create a classifier equivalent to a logistic regression with `softmax`

In [10]:
model = keras.Sequential([
    keras.layers.Dense(3, activation='softmax')
])

Or with one hidden layer

In [11]:
model2 = keras.Sequential([
    keras.layers.Dense(5, activation='relu'),
    # layers.Dropout(0.5),
    keras.layers.Dense(3, activation='softmax')
])

To try the network with one hidden layer, set `simple` to false

In [12]:
simple = False
if not simple:
    model = model2

## Fitting the Model

We compile and fit the model

In [13]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])
model.fit(X_scaled, Y_cat, epochs=50, batch_size=1)

Epoch 1/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5333 - loss: 1.1655
Epoch 2/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5556 - loss: 1.0823
Epoch 3/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5556 - loss: 1.0161
Epoch 4/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6000 - loss: 0.9620
Epoch 5/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6000 - loss: 0.9150
Epoch 6/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5778 - loss: 0.8747
Epoch 7/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5778 - loss: 0.8396
Epoch 8/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5778 - loss: 0.8100
Epoch 9/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5778 - loss: 0.7845
Epoch 10/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6000 - loss: 0.7631
Epoch 11/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5556 - loss: 0.7445
Epoch 12/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4444 - lo

### The weights

In [14]:
model.get_weights()

[array([[ 1.2156289 , -0.6371073 , -1.5077364 ,  0.6175317 , -0.5175538 ],
        [-0.43322068, -0.09682247,  0.7794163 , -0.35330892, -0.2799198 ]],
       dtype=float32),
 array([ 0.06063474, -0.20854026, -0.372982  ,  0.04202623,  0.5009015 ],
       dtype=float32),
 array([[-0.8283507 , -0.22673696,  1.1837318 ],
        [-0.51730156, -0.02844739,  0.56861883],
        [-0.20989665,  1.7233366 , -0.5659599 ],
        [-0.75228715, -0.16454837,  0.69117725],
        [ 0.72898215,  0.17824027, -0.5341    ]], dtype=float32),
 array([ 0.6857354 , -0.6099501 , -0.07578418], dtype=float32)]

## Prediction
### Probabilities

We compute the probabilities to belong to the classes for all the training set

In [15]:
Y_pred_proba = model.predict(X_scaled)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 


In [16]:
np.set_printoptions(precision=3, suppress=True)
Y_pred_proba

array([[0.685, 0.143, 0.172],
       [0.553, 0.347, 0.1  ],
       [0.512, 0.398, 0.091],
       [0.603, 0.28 , 0.117],
       [0.688, 0.143, 0.17 ],
       [0.575, 0.319, 0.106],
       [0.599, 0.285, 0.116],
       [0.639, 0.227, 0.134],
       [0.619, 0.257, 0.124],
       [0.488, 0.427, 0.085],
       [0.467, 0.453, 0.08 ],
       [0.576, 0.317, 0.107],
       [0.674, 0.172, 0.154],
       [0.584, 0.307, 0.11 ],
       [0.684, 0.143, 0.173],
       [0.216, 0.752, 0.032],
       [0.14 , 0.841, 0.019],
       [0.372, 0.567, 0.061],
       [0.136, 0.845, 0.019],
       [0.266, 0.693, 0.041],
       [0.106, 0.88 , 0.014],
       [0.265, 0.694, 0.041],
       [0.06 , 0.933, 0.007],
       [0.125, 0.858, 0.017],
       [0.063, 0.929, 0.008],
       [0.049, 0.945, 0.006],
       [0.149, 0.83 , 0.021],
       [0.18 , 0.795, 0.026],
       [0.098, 0.889, 0.013],
       [0.38 , 0.558, 0.062],
       [0.001, 0.002, 0.997],
       [0.001, 0.003, 0.997],
       [0.   , 0.001, 0.999],
       [0.

We recompute it with matrices

In [17]:
from keras.activations import softmax, relu
X = X_scaled.astype(np.float32)

if simple:
    print(softmax((X@model.get_weights()
          [0] + model.get_weights()[1]))[:4])
else:
    print(softmax((relu(X@model.get_weights()
          [0] + model.get_weights()[1]).to('cpu').numpy())
            @model.get_weights()[2] + model.get_weights()[3])[:4])

tensor([[0.6848, 0.1431, 0.1721],
        [0.5530, 0.3466, 0.1004],
        [0.5119, 0.3975, 0.0906],
        [0.6032, 0.2796, 0.1172]], device='mps:0')


### Classes

In [18]:
y_pred = np.argmax(Y_pred_proba, axis=-1)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2,
       2])

## Loss
We recompute the loss

For one observation

In [19]:
- Y_cat[0] @ np.log(Y_pred_proba[0]).T

np.float64(0.37857741117477417)

For the dataset

In [20]:
-np.mean(np.log(Y_pred_proba[range(0, len(y)), y]))

np.float32(0.38194638)

## Evaluation

With Keras

In [21]:
model.evaluate(X_scaled, Y_cat)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9333 - loss: 0.3819


[0.3819463551044464, 0.9333333373069763]

With sklearn

In [22]:
from sklearn.metrics import classification_report

print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91        15
           1       1.00      1.00      1.00        15
           2       1.00      0.80      0.89        15

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45



We computed the accuracy from the training set. This is not a good practice. We should use a dedicated test set instead.