# Chapter 16: Pretraining an Encoder: The BERT 2 Language Model
Fine-tuning BERT with the HuggingFace API

Programs from the book: [_Python for Natural Language Processing_](https://link.springer.com/book/9783031575488)

__Author__: Pierre Nugues

In [1]:
import os
import torch
import numpy as np

## Dataset

In [2]:
from datasets import load_dataset

In [3]:
imdb = load_dataset('stanfordnlp/imdb')

In [4]:
imdb

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

We can extract a small dataset for testing the whole pipeline

In [5]:
SMALL = True

In [6]:
if SMALL:
    imdb['train'] = imdb['train'].select(range(0, 25000, 100))
    imdb['test'] = imdb['test'].select(range(0, 25000, 100))

The dataset structure

In [7]:
imdb

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 250
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 250
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [8]:
train_set = imdb['train']

In [9]:
len(train_set)

250

In [10]:
train_set[0]

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far be

In [11]:
if not SMALL:
    print(train_set[12500])

In [12]:
test_set = imdb['test']

## Tokenizer

We create the tokenizer. These statements will download the model the first time we execute them. Again, it will be stored in a cache: `./~cache`

Alternatively, we can download it explicitely with the command:
```
git clone https://huggingface.co/distilbert-base-uncased
```


In [13]:
from transformers import AutoTokenizer

In [14]:
# model_name = "bert-base-uncased"
model_name = "distilbert-base-uncased"  # Downloaded automatically
# model_name = "~/.cache/distilbert-base-uncased" # Downloaded manually
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [15]:
train_set['text'][0]

'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, ev

In [16]:
tokens = tokenizer(train_set['text'][0])

In [17]:
tokens.keys()

KeysView({'input_ids': [101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 2107, 2004, 1996, 5148, 2162, 1998, 2679, 3314, 1999, 1996, 2142, 2163, 1012, 1999, 2090, 4851, 8801, 1998, 6623, 7939, 4697, 3619, 1997, 8947, 2055, 2037, 10740, 2006, 4331, 1010, 2016, 2038, 3348, 2007, 2014, 

In [18]:
tokens

{'input_ids': [101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 2107, 2004, 1996, 5148, 2162, 1998, 2679, 3314, 1999, 1996, 2142, 2163, 1012, 1999, 2090, 4851, 8801, 1998, 6623, 7939, 4697, 3619, 1997, 8947, 2055, 2037, 10740, 2006, 4331, 1010, 2016, 2038, 3348, 2007, 2014, 3689, 383

In [19]:
tokenizer.convert_ids_to_tokens(tokens['input_ids'])

['[CLS]',
 'i',
 'rented',
 'i',
 'am',
 'curious',
 '-',
 'yellow',
 'from',
 'my',
 'video',
 'store',
 'because',
 'of',
 'all',
 'the',
 'controversy',
 'that',
 'surrounded',
 'it',
 'when',
 'it',
 'was',
 'first',
 'released',
 'in',
 '1967',
 '.',
 'i',
 'also',
 'heard',
 'that',
 'at',
 'first',
 'it',
 'was',
 'seized',
 'by',
 'u',
 '.',
 's',
 '.',
 'customs',
 'if',
 'it',
 'ever',
 'tried',
 'to',
 'enter',
 'this',
 'country',
 ',',
 'therefore',
 'being',
 'a',
 'fan',
 'of',
 'films',
 'considered',
 '"',
 'controversial',
 '"',
 'i',
 'really',
 'had',
 'to',
 'see',
 'this',
 'for',
 'myself',
 '.',
 '<',
 'br',
 '/',
 '>',
 '<',
 'br',
 '/',
 '>',
 'the',
 'plot',
 'is',
 'centered',
 'around',
 'a',
 'young',
 'swedish',
 'drama',
 'student',
 'named',
 'lena',
 'who',
 'wants',
 'to',
 'learn',
 'everything',
 'she',
 'can',
 'about',
 'life',
 '.',
 'in',
 'particular',
 'she',
 'wants',
 'to',
 'focus',
 'her',
 'attention',
 '##s',
 'to',
 'making',
 'some',
 

In [20]:
tokenizer.model_max_length

512

In [21]:
tokenizer(train_set['text'][:3])

{'input_ids': [[101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 2107, 2004, 1996, 5148, 2162, 1998, 2679, 3314, 1999, 1996, 2142, 2163, 1012, 1999, 2090, 4851, 8801, 1998, 6623, 7939, 4697, 3619, 1997, 8947, 2055, 2037, 10740, 2006, 4331, 1010, 2016, 2038, 3348, 2007, 2014, 3689, 38

In [22]:
classics = [
    'Tell me, O Muse, of that hero',
    'Many cities did he visit',
    'Exiled from home am I ;']

In [23]:
tokenizer(classics, truncation=True, padding=True, max_length=512)

{'input_ids': [[101, 2425, 2033, 1010, 1051, 18437, 1010, 1997, 2008, 5394, 102], [101, 2116, 3655, 2106, 2002, 3942, 102, 0, 0, 0, 0], [101, 14146, 2013, 2188, 2572, 1045, 1025, 102, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]}

We tokenize the whole dataset with `map`

In [24]:
imdb_tokenized = imdb.map(lambda x: tokenizer(x['text'],
                                              truncation=True,
                                              padding=True,
                                              max_length=128),
                          batched=True)

In [25]:
imdb_tokenized['train'][:2]

{'text': ['I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far b

## Fine-tuning

In [26]:
model_name

'distilbert-base-uncased'

In [27]:
from transformers import AutoModelForSequenceClassification

num_labels = 2
model = (AutoModelForSequenceClassification
         .from_pretrained(model_name, num_labels=num_labels))

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_transform.bias    | UNEXPECTED | 
pre_classifier.bias     | MISSING    | 
classifier.bias         | MISSING    | 
pre_classifier.weight   | MISSING    | 
classifier.weight       | MISSING    | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


In [28]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(

In [29]:
from transformers import TrainingArguments

model_output_name = 'finetuned_imdb'
training_args = TrainingArguments(output_dir=model_output_name,
                                  num_train_epochs=2,
                                  learning_rate=2e-5,
                                  per_device_train_batch_size=32,
                                  per_device_eval_batch_size=32,
                                  weight_decay=0.01,
                                  eval_strategy='epoch',
                                  logging_strategy='no',  # we do not save ckeckpoints
                                  disable_tqdm=False)

In [30]:
def compute_accuracy(eval_output):
    labels_ids = eval_output.label_ids
    predictions = eval_output.predictions.argmax(axis=-1)
    return {'accuracy': np.mean(predictions == labels_ids)}

In [31]:
from transformers import Trainer

trainer = Trainer(model=model, args=training_args,
                  compute_metrics=compute_accuracy,
                  train_dataset=imdb_tokenized['train'],
                  eval_dataset=imdb_tokenized['test'],
                  processing_class=tokenizer)

In [32]:
trainer.train()

/opt/anaconda3/lib/python3.14/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)


Epoch,Training Loss,Validation Loss,Accuracy
1,No log,0.687787,0.612000
2,No log,0.683858,0.608000


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.14/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)


TrainOutput(global_step=16, training_loss=0.6860556602478027, metrics={'train_runtime': 10.8593, 'train_samples_per_second': 46.043, 'train_steps_per_second': 1.473, 'total_flos': 16558424832000.0, 'train_loss': 0.6860556602478027, 'epoch': 2.0})

In [33]:
trainer.save_model()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [34]:
metrics = trainer.evaluate()
metrics

Training Loss,Validation Loss,Epoch,Accuracy
No log,0.683858,2,0.608000


{'eval_loss': 0.6838580965995789, 'eval_accuracy': 0.608}

## Prediction with the model

We load the fine-tuned model

In [35]:
finetuned_model = AutoModelForSequenceClassification.from_pretrained(
    'finetuned_imdb')

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [36]:
input_ids = torch.LongTensor(imdb_tokenized['test']['input_ids'][-10:])
attention_mask = torch.LongTensor(
    imdb_tokenized['test']['attention_mask'][-10:])
labels = torch.LongTensor(imdb_tokenized['test']['label'][-10:])

In [37]:
input_ids

tensor([[  101,  1996,  3185,  ...,  1012,  2023,   102],
        [  101,  2108,  1037,  ...,  5632,  2296,   102],
        [  101,  2096,  2002,  ...,     0,     0,     0],
        ...,
        [  101,  4050,  1010,  ...,  2066,  2023,   102],
        [  101,  2023,  2143,  ...,  2522, 14515,   102],
        [  101,  4898,  1998,  ..., 12063,  1010,   102]])

In [38]:
labels

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [39]:
finetuned_model(input_ids, attention_mask=attention_mask, labels=labels)

SequenceClassifierOutput(loss=tensor(0.6863, grad_fn=<NllLossBackward0>), logits=tensor([[0.0021, 0.0519],
        [0.0399, 0.0457],
        [0.0232, 0.1028],
        [0.0347, 0.0059],
        [0.0357, 0.0270],
        [0.0522, 0.0416],
        [0.0598, 0.0611],
        [0.0428, 0.0607],
        [0.0112, 0.0515],
        [0.0402, 0.0339]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [40]:
finetuned_model(input_ids, attention_mask=attention_mask,
                labels=labels)[1].argmax(dim=-1)

tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 0])

In [41]:
torch.softmax(finetuned_model(
    input_ids, attention_mask=attention_mask, labels=labels)[1], dim=-1)

tensor([[0.4875, 0.5125],
        [0.4986, 0.5014],
        [0.4801, 0.5199],
        [0.5072, 0.4928],
        [0.5022, 0.4978],
        [0.5027, 0.4973],
        [0.4997, 0.5003],
        [0.4955, 0.5045],
        [0.4899, 0.5101],
        [0.5016, 0.4984]], grad_fn=<SoftmaxBackward0>)

## Prediction with a Pipeline

This includes the tokenizer

In [42]:
from transformers import pipeline

ftuned_model_name = 'finetuned_imdb'
classifier = pipeline('text-classification',
                      model=ftuned_model_name)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [43]:
classifier(['I loved it!!!', 'I hate this movie!'])

[{'label': 'LABEL_0', 'score': 0.5524218678474426},
 {'label': 'LABEL_0', 'score': 0.5640742778778076}]

## Freezing Layers

In [44]:
model_name

'distilbert-base-uncased'

In [45]:
cnt = 0
for p in model.pre_classifier.parameters():
    print(p)
    cnt += 1
    if cnt > 10:
        break

Parameter containing:
tensor([[-0.0052, -0.0163, -0.0124,  ..., -0.0260,  0.0017, -0.0071],
        [-0.0089,  0.0226, -0.0035,  ...,  0.0196,  0.0027,  0.0035],
        [-0.0341,  0.0049,  0.0009,  ...,  0.0116,  0.0227, -0.0069],
        ...,
        [-0.0213,  0.0046, -0.0195,  ..., -0.0223, -0.0209, -0.0104],
        [-0.0177, -0.0134,  0.0429,  ..., -0.0073, -0.0165,  0.0007],
        [ 0.0398, -0.0090,  0.0097,  ...,  0.0103, -0.0167,  0.0111]],
       device='mps:0', requires_grad=True)
Parameter containing:
tensor([-7.1346e-05,  7.0475e-05, -9.3509e-06,  0.0000e+00, -7.9380e-06,
         1.8899e-06, -8.5134e-05, -5.7152e-05, -6.5961e-05,  8.8612e-05,
         9.2645e-05,  9.2906e-05, -1.1296e-04,  0.0000e+00, -1.0469e-05,
        -1.1016e-04, -5.6552e-06,  0.0000e+00, -4.9175e-05,  0.0000e+00,
         9.2608e-05,  1.2765e-05,  9.3864e-05,  1.0356e-04, -4.7946e-05,
         8.1432e-05, -5.6395e-05,  3.5268e-05, -5.3406e-05, -2.3781e-05,
         9.2649e-05, -9.5374e-05, -8.0994

In [46]:
def count_parameters(model):
    total = 0
    trainable = 0
    for params in model.parameters():
        total += params.numel()
        if params.requires_grad:
            trainable += params.numel()
    return {'total': total, 'trainable': trainable}

In [47]:
count_parameters(model)

{'total': 66955010, 'trainable': 66955010}

We reload the original model and we freeze some layers

In [48]:
from transformers import AutoModelForSequenceClassification

num_labels = 2
model_freezed = (AutoModelForSequenceClassification
                 .from_pretrained(model_name,
                                  num_labels=num_labels,
                                  attn_implementation='eager'))

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_transform.bias    | UNEXPECTED | 
pre_classifier.bias     | MISSING    | 
classifier.bias         | MISSING    | 
pre_classifier.weight   | MISSING    | 
classifier.weight       | MISSING    | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


In [49]:
model_freezed

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(

In [50]:
count_parameters(model_freezed)

{'total': 66955010, 'trainable': 66955010}

In [51]:
count_parameters(model_freezed.pre_classifier)

{'total': 590592, 'trainable': 590592}

In [52]:
count_parameters(model_freezed.classifier)

{'total': 1538, 'trainable': 1538}

In [53]:
for param in model_freezed.parameters():
    param.requires_grad = False

In [54]:
for param in model_freezed.pre_classifier.parameters():
    param.requires_grad = True

for param in model_freezed.classifier.parameters():
    param.requires_grad = True

In [55]:
count_parameters(model_freezed)

{'total': 66955010, 'trainable': 592130}

This is to be compared with the original model

In [56]:
count_parameters(model)

{'total': 66955010, 'trainable': 66955010}

In [57]:
from transformers import Trainer

trainer = Trainer(model=model_freezed, args=training_args,
                  compute_metrics=compute_accuracy,
                  train_dataset=imdb_tokenized['train'],
                  eval_dataset=imdb_tokenized['test'],
                  processing_class=tokenizer)

In [58]:
trainer.train()

Epoch,Training Loss,Validation Loss,Accuracy
1,No log,0.693781,0.492000
2,No log,0.693204,0.520000


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.14/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)


TrainOutput(global_step=16, training_loss=0.6943986415863037, metrics={'train_runtime': 4.3907, 'train_samples_per_second': 113.878, 'train_steps_per_second': 3.644, 'total_flos': 16558424832000.0, 'train_loss': 0.6943986415863037, 'epoch': 2.0})

In [59]:
metrics = trainer.evaluate()
metrics

Training Loss,Validation Loss,Epoch,Accuracy
No log,0.693204,2,0.520000


{'eval_loss': 0.6932036280632019, 'eval_accuracy': 0.52}